### ISSUE TITLE
I can't install the extension manually

### ISSUE THREAD

**Issue by BiancaPereira** [notionblog/NotionThemes#12]
I'm trying to install the extension on Chrome (MacOS), since we can not install it via Chrome Store (#6 #10). 

Here are the steps I did: 

1. Downloaded the `.zip` file from the README (or in [this link](https://github.com/notionblog/NotionThemes/releases/tag/0.0.2)).
2. Unzip the `chrome` folder.
3. Opened `chrome://extensions/`.
4. Enabled **developer mode**.
5. Dragged the `chrome` folder.

Error: **Unable to load manifest.**

![image](https://github.com/notionblog/NotionThemes/assets/16962057/95bcfc85-cfa4-4128-a2d0-7d27ae1c9af4)

**Comment by yudax42** [comment]
duplicate #13
