### ISSUE TITLE
Website shows "Add to Safari" button when using Safari

### ISSUE THREAD

**Issue by KElee01** [notionblog/NotionThemes#4]
It's very confusing when I clicked the "Add to Safari" button but it opened a link to Chrome Web store. Simply change it to "Not Support Safari" would be okay to me. Nice work btw.

**Comment by yudax42** [comment]
Hi @KElee01,
Oh sorry, The safari version is still not ready, for now, the extensions work only on Chrome/Brave/Firefox/Opera/Edge. 
Thanks for the feedback!
